services:
  - type: web
    name: gym-management-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn gymshalaMngSys.wsgi:application
